# change prefix key to C-a
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# use | and = for splitting windows
# new panes open in the same directory
unbind '"'
unbind %
bind | split-window -h -c '#{pane_current_path}'
bind = split-window -v -c '#{pane_current_path}'

# use Alt + arrow keys without the prefix key for faster pane switching
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R

# simple options
set -g base-index 1                                 # new windows start at index 1 instead of 0
set -g history-file $XDG_STATE_HOME/tmux/history    # save tmux command history
set -g mouse on                                     # enable mouse
set -g escape-time 50                               # set slightly higher than 0 to prevent tmux from printing random escape sequences at startup on slower terminals

# ---- tpm --------------------

# installed plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin '2kabhishek/tmux2k'

set -g @tmux2k-theme 'onedark'
set -g @tmux2k-icons-only false
set -g @tmux2k-show-powerline false
set -g @tmux2k-refresh-rate 3
set -g @tmux2k-window-list-alignment 'left'
set -g @tmux2k-left-plugins 'session'
set -g @tmux2k-right-plugins 'cpu time'
set -g @tmux2k-time-format '%H:%M:%S %d.%m.%Y'

# need to set plugin path for automatic installation (see https://github.com/tmux-plugins/tpm/issues/105)
setenv -g TMUX_PLUGIN_MANAGER_PATH "$XDG_STATE_HOME/tmux/plugins/"

# automatically install tpm and plugins on new installations
if "test ! -d $XDG_STATE_HOME/tmux/plugins/tpm" "run 'git clone https://github.com/tmux-plugins/tpm $XDG_STATE_HOME/tmux/plugins/tpm && $XDG_STATE_HOME/tmux/plugins/tpm/bin/install_plugins'"

# initialize tmux plugin manager (keep this line at the very bottom of tmux.conf)
run "$XDG_STATE_HOME/tmux/plugins/tpm/tpm"
